blank_issues_enabled: true
contact_links:
  - name: Start a discussion
    about: 🗨 Start a friendly conversation with the other members of the community about the samples in this repository.
    url: https://github.com/thynclabs/{repository}/discussions
