name: 💡 Suggestion
description: Suggest an enhancement to make one of features even better
labels: ['Needs: Triage :mag:', 'type:enhancement']

body:
  - type: markdown
    attributes:
      value: |

        Thank you for your suggestion! Use the sections below to submit a suggestion **only** if it's related to samples in this repo.

        - Suggestions that do not follow the below template will automatically be closed
        - All ideas are welcome - let's build something together!
        - This repo is maintained by volunteers. Please be courteous and patient. 🙂
        - Remember to include sufficient details and context.
        - If you have multiple suggestions please submit them separately so we can track resolution.
        - Screenshots are always helpful (just paste any images right here in the suggestion)

  - type: input
    id: function
    validations:
      required: true
    attributes:
      label: Function
      description: |
        Which function are you talking about

        Use the function name.

  - type: textarea
    id: suggestion
    attributes:
      label: Suggestion
      description: What would you like to see improved?
      placeholder: The more details, the better
    validations:
      required: true


  - type: dropdown
    id: willing-to-help
    attributes:
      label: Are you willing to help?
      description: Would you be willing to help us make this improvement?
      options:
        - "Yes"
        - "No"
    validations:
      required: true
