name: Default Repository Setup

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test
        uses: thynclabs/template-transformer-and-cleanup@0.0.10
        with:
          text: script

      - name: Print repository created message
        run: echo "A new repository has been created and initialized!"
