name: Default Repository Setup

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test
        uses: thynclabs/template-transformer-and-cleanup@v0.0.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print repository created message
        run: echo "A new repository has been created and initialized!"
